### ISSUE TITLE
Not possible to download via package manager on 0.16.0

### ISSUE THREAD

**Issue by thisredone** [bakkemo/elm-collision#4]
From the commit history I see that there was progress made to port this very nice package to 0.16.0 but I'm currently unable to download it through package manager and also http://package.elm-lang.org/ is listing it as not yet updated.

**Comment by bakkemo** [comment]
I don't know what to tell you. elm-package publish worked fine. I bumped the version number and did it again:
λ elm-package publish
Verifying bakkemo/elm-collision 2.0.1 ...
Version number 2.0.1 verified (PATCH change, 2.0.0 => 2.0.1)
Success!

not sure what else I can do.

**Comment by thisredone** [comment]
It did work this time :)
and also elm package repository shows it currently as up to date so I guess: thank you!
